/**
 * Clase servant con los campos de la BBDD
*/

export class Servant {
    constructor(
        public num_entrada: number,
        public nombre: string,
        public imagen: string,
        public icon: string,
        public clase: string,
        public rareza: number,
        public coste: number,
        public vida_max: number,
        public atq_max: number,
        public vida_max_100: number,
        public atq_max_100: number,
        public vida_max_120: number,
        public atq_max_120: number,
        public atributo: string,
        public abs_estrellas: number,
        public gen_estrellas: number,
        public gen_np_atq: number,
        public gen_np_def: number,
        public death_rate: number,
        public alineacion: string,
        public genero: string,
        public trato: string,
        public golpes_quick: number,
        public golpes_arts: number,
        public golpes_buster: number,
        public golpes_extra: number,
        public cartas: string,
        public etiquetas: string,
        public skill_1: string,
        public skill_1_desc: string,
        public skill_2: string,
        public skill_2_desc: string,
        public skill_3: string,
        public skill_3_desc: string,
        public append_skill_3: string,
        public append_skill_desc_3: string,
        public pasiva1: string,
        public pasiva1_desc: string,
        public pasiva2: string,
        public pasiva2_desc: string,
        public pasiva3: string,
        public pasiva3_desc: string,
        public pasiva4: string,
        public pasiva4_desc: string,
        public pasiva5: string,
        public pasiva5_desc: string,
        public pasiva6: string,
        public pasiva6_desc: string,
        public pasiva7: string,
        public pasiva7_desc: string,
        public pasiva8: string,
        public pasiva8_desc: string,
        public pasiva9: string,
        public pasiva9_desc: string,
        public pasiva10: string,
        public pasiva10_desc: string,
        public np: string,
        public np_desc: string,
        public esencia_bond: string,
        public esencia_bond_imagen: string,
        public esencia_bond_desc: string,
        public id?: number,
        
    ) { }

}